#!/bin/sh
#
# SigScale Global Inc.
#
# Start Erlang/OTP Embedded system.
#
# Usage: start [Erlang Emulator Flags]

if [ -z "$NODENAME" ]
then
   NODENAME=usekeeper
fi

if [ -z "$ROOTDIR" ]
then
   ROOTDIR=/usr/lib/erlang
fi

if [ -z "$RELDIR" ]
then
   RELDIR=$ROOTDIR/releases
fi
START_ERL_DATA=$RELDIR/start_erl.data

if [ $# -gt 0 ]
then
	ERLARGS="$*"
	shift $#
else
	ERLARGS="+K true +Bi -boot_var OTPHOME ${ROOTDIR} -sname ${NODENAME}"
fi

export RUN_ERL_LOG_ALIVE_IN_UTC=1
export RUN_ERL_LOG_GENERATIONS=10
export RUN_ERL_LOG_MAXSIZE=1048576
export RUN_ERL_DISABLE_FLOWCNTRL

export TERM=xterm
export ROOTDIR
export RELDIR
export START_ERL_DATA
export ERLARGS

$ROOTDIR/bin/run_erl /tmp/ log \
	'exec ${ROOTDIR}/bin/start_erl ${ROOTDIR} ${RELDIR} \
	${START_ERL_DATA} ${ERLARGS}'

