apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: usekeeper
  labels:
    oda.tmforum.org/componentName: usekeeper
spec:
  type: ocs
  selector:
    matchLabels:
     oda.tmforum.org/componentName: usekeeper
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment  
  version: "1.0.0"
  description: "SigScale Online Charging System (OCS)" 
  maintainers:
    - name: SigScale
      email: support@sigscale.com
  owners:
    - name: SigScale
      email:  support@sigscale.com 
  coreFunction:
    exposedAPIs: 
    - name: party
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      implementation: usekeeper-service
      path: /party/v4/individual
      port: 8080
    - name: usageSpecification
      specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635_UsageManagement_swagger_AP1144.json
      implementation: usekeeper-service
      path: /usageManagement/v4/usageSpecification
      port: 8080
    - name: usageSpecification
      specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635_UsageManagement_swagger_AP1144.json
      implementation: usekeeper-service
      path: /usageManagement/v4/usage
      port: 8080
    dependantAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usekeeper
  labels:
    app.kubernetes.io/name: ocs
    app: usekeeper
    oda.tmforum.org/componentName: usekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ocs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocs
        app.kubernetes.io/component: 3gpp-ocf
        app.kubernetes.io/component: rest
        app: usekeeper
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: ocs-install
        image: sigscale/ocs
        command:
        - sh
        - bin/initialize
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      containers:
      - name: ocs
        image: sigscale/ocs
        ports:
        - name: diameter
          protocol: TCP
          containerPort: 3868
        - name: radius
          protocol: UDP
          containerPort: 1812
        - name: radius-acct
          protocol: UDP
          containerPort: 1813
        - name: http
          protocol: TCP
          containerPort: 8080
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      volumes:
      - name: db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: usekeeper-service
  labels:
    app: usekeeper
    oda.tmforum.org/componentName: usekeeper
spec:
  ports:
  - port: 8080
    targetPort: http
    name: usekeeper-service
  type: LoadBalancer
  selector:
    app: usekeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocs-data
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
